- name: Deploy Petclinic App
  hosts: petclinic
  gather_facts: no
  tasks:
    - name: Stop running jar file
      ansible.builtin.command: pkill -f /app/spring-petclinic-3.0.0-SNAPSHOT.jar
      become: yes
      ignore_errors: yes

    - name: Run jar file.
      ansible.builtin.command: nohup /usr/local/openjdk-17/bin/java -jar /app/spring-petclinic-3.0.0-SNAPSHOT.jar &
